language: node_js
node_js:
- node
deploy:
  api_key:
    secure: mSlps4g5QVhbZtp1sN4pxKNEb628xW8IA/IFH5dFWquOyzUEUj9s2npHAi8a5QA4busOPISrXfCEg+YwmliYk4azlqXXA0hBJ8vOmY+O/WpR7PrS7h6Lxw7ReWZf3xWo8lEltrC0M6SblwjKp6VbesaXKoLKk1Fgv4Hkm2PuIp3chPj+kzoUbOR5wm2ugLi+ON0/COu0VZ3t2MflY3xUfSkr09Daw0gJEtNtYwpXw6hYmnvXUWX0vcdNV0nRy+XYGPA8PEBTRNIEsQ0JTmVAVMnQQE2cIgYPA8D53lBR85I37Pmdx/21hhDS4cUSkvt4engqV0PHYxdDsDNtHcHaq4JRKuGeoV4P9TXMmT+9B2WYaAFEyxn65En4bdG5cV9T8zHNcJp7qX5Hle83+SfyKIWgx2ad38jaePcd1Dwx4sWWE4zQsJ0fzpoBMtd2Hay2X7xLNtBtFYdQbK4CYOPWSUN65D9HFlOlCg2Ki8fdKuLwVa31JV3bKM4SkSQSC8KKiXdmlOK2FFiubB5CzGmte9lt2i6UnhGVWUQxL4VEe9pru/DbDe9VR/HBgDeyE0+hSTUoYZW/2I2gb21/vG5RcxnZd+2FD5wAKrpZ8WgAnA4FcHcFUGBSi9pN4nw/QiwUh17wI5ZPGXp3MZQGsB8OabMuTHR1FBGFq3j+aWJtPUE=
